# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CalcSolverSsr

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        cd CalcSolverSsr
        npm install
        npm run build --if-present
        npm run test --if-present
        cd ..

    - name: 'Tar files'
      run: tar -cvf my_files.tar .
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: my_files.tar

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app
        
    - name: 'UnTar files'
      run: tar -xvf my_files.tar
      
    - name: yarn
      run: |
        cd CalcSolverSsr
        yarn start
        cd ..
        
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CalcSolverSsr'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f3d7799175e43788f99a6a6a1f96ac8 }}
        package: .
        

